### ISSUE TITLE
urbackup

### ISSUE THREAD

**Issue by manishalankala** [finalwebsites/mybackup#1]
Hi Olaf,

i had refered to some of your old post related to urbackup.

i have similar issue while clicking on restore icon from the urbackup web ui but it doesn't work.

let me know if you have any suggestions here. how did you solve that

Server -ubuntu - latest version ur backup

Client -ubuntu - latest version ur backup

Reference - https://github.com/manishalankala/urbackup

**Comment by finalwebsites** [comment]
Hi,
please don't "trash" other projects with unrelated questions.
To your question, I didn't solved it. After some time (weeks or months) the button appears. I have no idea why :)
